#ifndef CONFIG_H_
#define CONFIG_H_

#ifndef MAXIMUM_KEYBOARD_KEYS
#define MAXIMUM_KEYBOARD_KEYS 512
#endif

#ifndef MAXIMUM_MOUSE_BUTTONS
#define MAXIMUM_MOUSE_BUTTONS 8
#endif

#ifndef MAXIMUM_KEYPRESSED_QUEUE
#define MAXIMUM_KEYPRESSED_QUEUE 16
#endif

#ifndef MAXIMUM_SHADER_LOCS
#define MAXIMUM_SHADER_LOCS 16
#endif

#ifndef MAXIMUM_BATCH_RENDERER_VERTICES
#define MAXIMUM_BATCH_RENDERER_VERTICES (32*1024)
#endif

#ifndef MAXIMUM_BATCH_RENDERER_ELEMENTS
#define MAXIMUM_BATCH_RENDERER_ELEMENTS (64*1024)
#endif

#ifndef MAXIMUM_BATCH_RENDERER_ACTIVE_TEXTURES
#define MAXIMUM_BATCH_RENDERER_ACTIVE_TEXTURES 8
#endif

#ifndef POSITION_SHADER_ATTRIBUTE_LOCATION
#define POSITION_SHADER_ATTRIBUTE_LOCATION 0
#endif 

#ifndef COLOR_SHADER_ATTRIBUTE_LOCATION
#define COLOR_SHADER_ATTRIBUTE_LOCATION 1
#endif // COLOR_SHADER_ATTRIBUTE_LOCATION

#ifndef TEXCOORDS_SHADER_ATTRIBUTE_LOCATION
#define TEXCOORDS_SHADER_ATTRIBUTE_LOCATION 2
#endif // TEXCOORDS_SHADER_ATTRIBUTE_LOCATION

#ifndef TEXTURE_INDEX_SHADER_ATTRIBUTE_LOCATION
#define TEXTURE_INDEX_SHADER_ATTRIBUTE_LOCATION 3
#endif // TEXTURE_INDEX_SHADER_ATTRIBUTE_LOCATION

#ifndef TEXTURE_SAMPLERS_SHADER_UNIFORM_LOCATION
#define TEXTURE_SAMPLERS_SHADER_UNIFORM_LOCATION 4
#endif // TEXTURE_SAMPLERS_SHADER_UNIFORM_LOCATION

#ifndef PROJECTION_MATRIX_SHADER_UNIFORM_LOCATION
#define PROJECTION_MATRIX_SHADER_UNIFORM_LOCATION 5
#endif // PROJECTION_MATRIX_SHADER_UNIFORM_LOCATION

#ifndef VIEW_MATRIX_SHADER_UNIFORM_LOCATION
#define VIEW_MATRIX_SHADER_UNIFORM_LOCATION 6
#endif // VIEW_MATRIX_SHADER_UNIFORM_LOCATION

#ifndef MODEL_MATRIX_SHADER_UNIFORM_LOCATION
#define MODEL_MATRIX_SHADER_UNIFORM_LOCATION 7
#endif // MODEL_MATRIX_SHADER_UNIFORM_LOCATION

#ifndef POSITION_SHADER_ATTRIBUTE_NAME
#define POSITION_SHADER_ATTRIBUTE_NAME "a_Position"
#endif // POSITION_SHADER_ATTRIBUTE_NAME

#ifndef COLOR_SHADER_ATTRIBUTE_NAME
#define COLOR_SHADER_ATTRIBUTE_NAME "a_Color"
#endif // COLOR_SHADER_ATTRIBUTE_NAME

#ifndef TEXCOORDS_SHADER_ATTRIBUTE_NAME
#define TEXCOORDS_SHADER_ATTRIBUTE_NAME "a_TexCoords"
#endif // TEXCOORDS_SHADER_ATTRIBUTE_NAME

#ifndef TEXTURE_INDEX_SHADER_ATTRIBUTE_NAME
#define TEXTURE_INDEX_SHADER_ATTRIBUTE_NAME "a_TextureIndex"
#endif // TEXTURE_INDEX_SHADER_ATTRIBUTE_NAME

#ifndef TEXTURE_SAMPLERS_SHADER_UNIFORM_NAME
#define TEXTURE_SAMPLERS_SHADER_UNIFORM_NAME "u_Textures"
#endif // TEXTURE_SAMPLERS_SHADER_UNIFORM_NAME

#ifndef PROJECTION_MATRIX_SHADER_UNIFORM_NAME
#define PROJECTION_MATRIX_SHADER_UNIFORM_NAME "u_Projection"
#endif // PROJECTION_MATRIX_SHADER_UNIFORM_NAME

#ifndef VIEW_MATRIX_SHADER_UNIFORM_NAME
#define VIEW_MATRIX_SHADER_UNIFORM_NAME "u_View"
#endif // VIEW_MATRIX_SHADER_UNIFORM_NAME

#ifndef MODEL_MATRIX_SHADER_UNIFORM_NAME
#define MODEL_MATRIX_SHADER_UNIFORM_NAME "u_Model"
#endif // MODEL_MATRIX_SHADER_UNIFORM_NAME

#endif // CONFIG_H_
